version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "ac3"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-cmsrrbsegy3t"
s3_prefix = "ac3"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
